//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "change_requests")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub idempotency_key: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::change_commits::Entity")]
    ChangeCommits,
    #[sea_orm(has_many = "super::change_request_add_files::Entity")]
    ChangeRequestAddFiles,
}

impl Related<super::change_commits::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChangeCommits.def()
    }
}

impl Related<super::change_request_add_files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChangeRequestAddFiles.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
