//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "delta_files")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub delta_log_id: i64,
    pub path: String,
    pub size: i64,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::delta_logs::Entity",
        from = "Column::DeltaLogId",
        to = "super::delta_logs::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DeltaLogs,
}

impl Related<super::delta_logs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DeltaLogs.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
