//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "delta_logs")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::delta_files::Entity")]
    DeltaFiles,
}

impl Related<super::delta_files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DeltaFiles.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
