//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

pub use super::change_commits::Entity as ChangeCommits;
pub use super::change_request_add_files::Entity as ChangeRequestAddFiles;
pub use super::change_requests::Entity as ChangeRequests;
