//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "change_request_idempotency_keys")]
pub struct Model {
    #[sea_orm(
        primary_key,
        auto_increment = false,
        column_type = "VarBinary(StringLen::None)"
    )]
    pub key: Vec<u8>,
    #[sea_orm(unique)]
    pub change_request_id: i64,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub expires_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::change_requests::Entity",
        from = "Column::ChangeRequestId",
        to = "super::change_requests::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ChangeRequests,
}

impl Related<super::change_requests::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChangeRequests.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
