//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "current_files")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub user_table_id: i64,
    pub stream_id: i64,
    pub partition_time: DateTimeWithTimeZone,
    pub file_id: i64,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub file_path_xxh3: Vec<u8>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub file_lock_key: Option<Vec<u8>>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::file_locks::Entity",
        from = "Column::FileLockKey",
        to = "super::file_locks::Column::Key",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    FileLocks,
    #[sea_orm(
        belongs_to = "super::files::Entity",
        from = "Column::FileId",
        to = "super::files::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Files,
    #[sea_orm(
        belongs_to = "super::user_tables::Entity",
        from = "Column::UserTableId",
        to = "super::user_tables::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    UserTables,
}

impl Related<super::file_locks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FileLocks.def()
    }
}

impl Related<super::files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Files.def()
    }
}

impl Related<super::user_tables::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserTables.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
