//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "file_locks")]
pub struct Model {
    #[sea_orm(
        primary_key,
        auto_increment = false,
        column_type = "VarBinary(StringLen::None)"
    )]
    pub key: Vec<u8>,
    pub user_table_id: i64,
    pub stream_id: i64,
    pub expire_at: DateTimeWithTimeZone,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::current_files::Entity")]
    CurrentFiles,
}

impl Related<super::current_files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CurrentFiles.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
