//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "files")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub user_table_id: i64,
    pub stream_id: i64,
    pub partition_time: DateTimeWithTimeZone,
    pub path: String,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub path_xxh3: Vec<u8>,
    pub size: i64,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::current_files::Entity")]
    CurrentFiles,
    #[sea_orm(has_many = "super::file_column_statistics::Entity")]
    FileColumnStatistics,
    #[sea_orm(has_one = "super::file_metadata::Entity")]
    FileMetadata,
    #[sea_orm(
        belongs_to = "super::user_tables::Entity",
        from = "Column::UserTableId",
        to = "super::user_tables::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    UserTables,
}

impl Related<super::current_files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CurrentFiles.def()
    }
}

impl Related<super::file_column_statistics::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FileColumnStatistics.def()
    }
}

impl Related<super::file_metadata::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FileMetadata.def()
    }
}

impl Related<super::user_tables::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserTables.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
