//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "files")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub user_table_id: i64,
    pub stream_id: i64,
    pub partition_time: DateTimeWithTimeZone,
    pub path: String,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub path_xxh3: Vec<u8>,
    pub size: i64,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::current_files::Entity")]
    CurrentFiles,
}

impl Related<super::current_files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CurrentFiles.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
