//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user_tables")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "Text", unique)]
    pub name: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::change_requests::Entity")]
    ChangeRequests,
    #[sea_orm(has_many = "super::commits::Entity")]
    Commits,
    #[sea_orm(has_many = "super::current_files::Entity")]
    CurrentFiles,
    #[sea_orm(has_many = "super::file_locks::Entity")]
    FileLocks,
    #[sea_orm(has_many = "super::files::Entity")]
    Files,
}

impl Related<super::change_requests::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChangeRequests.def()
    }
}

impl Related<super::commits::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Commits.def()
    }
}

impl Related<super::current_files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CurrentFiles.def()
    }
}

impl Related<super::file_locks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FileLocks.def()
    }
}

impl Related<super::files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Files.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
